jasypt:
  encryptor:
    password: ${ENC_KEY:}
    algorithm: PBEWITHMD5ANDTRIPLEDES
    stringOutputType: base64

spring:
  flyway:
    locations: classpath:db/migration/mysql
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

security:
  jwt:
    expirationMinutes: 43200
    signing:
      key: ${JWT_SIGNING_KEY:}
  password:
    reset:
      validityMinutes: 15

app:
  domain: http://localhost:8080

logging:  
  level:    
    org.flywaydb: DEBUG